loire-common: camera: Include missing fcntl.h
QCamera2/util/QCameraHALPP.cpp:410:30: error: use of undeclared identifier 'O_RDWR'
    int file_fd = open(name, O_RDWR | O_CREAT, 0777);
                             ^
QCamera2/util/QCameraHALPP.cpp:410:39: error: use of undeclared identifier 'O_CREAT'
    int file_fd = open(name, O_RDWR | O_CREAT, 0777);

QCamera2/util/QCameraBokeh.cpp:825:34: error: use of undeclared identifier 'O_RDWR'
    int file_fd = open(filename, O_RDWR | O_CREAT, 0777);
                                 ^
QCamera2/util/QCameraBokeh.cpp:825:43: error: use of undeclared identifier 'O_CREAT'
    int file_fd = open(filename, O_RDWR | O_CREAT, 0777);
                                          ^
QCamera2/util/QCameraBokeh.cpp:990:34: error: use of undeclared identifier 'O_RDWR'
    int file_fd = open(filename, O_RDWR | O_CREAT, 0777);
                                 ^
QCamera2/util/QCameraBokeh.cpp:990:43: error: use of undeclared identifier 'O_CREAT'
    int file_fd = open(filename, O_RDWR | O_CREAT, 0777);

Change-Id: Ibd9ff844caee8cebe7d131cb0bfade4daf48d374